#!/bin/bash

child_ps(){
    local parent_pid=$1
    local sub_pids=$(ps --ppid "$parent_pid" -o pid --no-headers)
    for cpid in $sub_pids; do
        [ -z "$cpid" ] && continue
        local mem=$(cat /proc/$cpid/status | grep -E 'VmRSS|VmSwap'| gawk '{ sum += $2 }; END { print sum }')
        total_mem=$((total_mem + mem))
        local rss=$(ps -p $cpid -o rss --no-headers)
        total_rss=$((total_rss + rss))
		child_ps "$cpid"   # Recursive call to get the RSS of all child processes
    done
}

parent_ps(){
	local pid=$1
	local mem=$(cat /proc/$pid/status | grep -E 'VmRSS|VmSwap'| gawk '{ sum += $2 }; END { print sum }')
	total_mem=$((total_mem + mem))
	local rss=$(ps -p $pid -o rss --no-headers)
	total_rss=$((total_rss + rss))
	child_ps "$pid"
}

echo "checking zapzap for overload"
if flatpak ps | grep -q zap; then
	total_mem=0
	total_rss=0
	if ps -p $(flatpak ps| awk '$3 ~ /zap/ {print $2}')| grep zap; then
		for pid in $(flatpak ps| awk '$3 ~ /zap/ {print $2}'); do
			parent_ps "$pid"
		done
	else
		parent_ps "$(ps -eo pid,cmd| awk '$3 ~ /zap/ {print $1; exit}')"
	fi
	if [[ $total_rss -gt 1048576 || $total_mem -gt 1048576 ]]; then
		echo "restarting zapzap"
		flatpak kill com.rtosta.zapzap
		pid=$(ps -C flatpak-portal -o pid --no-headers)
		if [ -n "$pid" ]; then
			cpids=$(ps --ppid $pid -o pid --no-headers)
		fi
		for spid in $cpids; do
			kill $spid
		done
		flatpak run com.rtosta.zapzap @@u %u @@&
		disown
	fi
fi

exit 0