#!/bin/bash

LOGFILE="$HOME/.anacron/anacron.log"  # Specify the path for the log file
crontab="$HOME/.anacron/crontab"
reboot="true"
[ -f "$HOME/.anacron/timer_start" ] && timer_start="$(cat "$HOME/.anacron/timer_start")"
[ "$timer_start"=="$(systemctl --user status anacron-user.timer| tail -n 1)" ]&&reboot="false"
$reboot && systemctl --user status anacron-user.timer| tail -n1 >"$HOME/.anacron/timer_start"
current_time=$(date '+%-M %-H %-d %-m %-w')
cmd=$(~/.anacron/rangeToRegex.py "$(sed '/^ \?#/d;/^ \?[A-Za-z_][A-Za-z0-9_]*=/d;/^$/d;s|#.*||g' $crontab)" "$current_time")
eval "$(grep '^ \?[A-Za-z_][A-Za-z0-9_]*=' $crontab)" "$(echo -e $(echo $cmd| sed -z '/[^\\]%/ s|%|\n|'))"
if [ ! -d $HOME/.anacron/cron.d/ ] || [ ! -r $HOME/.anacron/cron.d/* ];then exit 0;fi
for file in $HOME/.anacron/cron.d/*;do
	if [ $(sed '/^ \?#/d;/^ \?[A-Za-z_][A-Za-z0-9_]*=/d;/^$/d;s|#.*||g' $file)=='' ];then continue;fi
	lines=$(~/.anacron/rangeToRegex.py "$(sed '/^ \?#/d;/^ \?[A-Za-z_][A-Za-z0-9_]*=/d;/^$/d;s|#.*||g' $file)" "$current_time")
	cmd="$(echo "$lines"| awk '{if ($0!="") print "sudo -u "$0}')"
	if [[ ! -n $cmd ]];then continue;fi
	eval "$(grep '^ \?[A-Za-z_][A-Za-z0-9_]*=' $file)" "$(echo -e $(echo $cmd| sed -z '/[^\\]%/ s|%|\n|'))"
done
exit 0