#!/bin/bash

LOGFILE="$HOME/.anacron/anacron.log"  # Specify the path for the log file
crontab="$HOME/.anacron/crontab"
{
	current_time=$(date '+%-M %-H %-d %-m %-w')
	cmd=$(.anacron/rangeToRegex.py "$(sed '/^ \?#/d;/^ \?[A-Za-z_][A-Za-z0-9_]*=/d;/^$/d;s|#.*||g' $crontab)" "$current_time")
	eval "$(grep '^ \?[A-Za-z_][A-Za-z0-9_]*=' $crontab)" "$(echo $cmd| tr '%' '\n')"
	for file in $HOME/.anacron/cron.d/*;do
		lines=$(.anacron/rangeToRegex.py "$(sed '/^ \?#/d;/^ \?[A-Za-z_][A-Za-z0-9_]*=/d;/^$/d;s|#.*||g' $file)" "$current_time")
		cmd="$(echo "$lines"| awk '{if ($0!="") print "sudo -u "$0}'| tr '\t' ' '| tr '%' '\n')"
		if [[ ! -n $cmd ]];then
			continue
		fi
		eval "$(grep '^ \?[A-Za-z_][A-Za-z0-9_]*=' $file)" "$cmd"
	done
}
exit 0