#!/bin/sh
#
# anacron's cron script
#
# This script updates anacron time stamps. It is called through run-parts
# either by anacron itself or by cron.
#
# The script is called "0anacron" to assure that it will be executed
# _before_ all other scripts.

test -x /usr/sbin/anacron -S /home/david/.anacron/spool/ -t /home/david/.anacron/anacrontab || exit 0
anacron -S /home/david/.anacron/spool/ -t /home/david/.anacron/anacrontab -u cron.daily