#!/bin/sh

find /home/david/Documents/JCT/ -name '*cache*' -exec trash {} +
find /home/david/Documents/JCT/ -empty -type d -exec trash {} +
find /home/david/Documents/JCT/ -empty -type d -exec trash {} +
find /home/david/Documents/JCT/ -empty -type d -exec trash {} +
#~ /home/david/Documents/JCT/$(ls -R|grep -E 'cache|pycache')
#~ trash -rd /mnt/reserves/JCT/$(ls -R|grep -E 'cache|pycache')
GLOBEIGNORE=*cache*:.*:*.*.*:*.zip
cp -r -u /home/david/Documents/JCT/* /mnt/reserves/JCT/ #| zenity --progress --percentage=0 --auto-kill --auto-close --text="updating 'reserves'..."
#~ cp -r -u /home/david/Documents/JCT/*?.* /media/david/shared/JCT/
while true; do
	if $(ping 8.8.8.8 -c 64| grep ttl -q); then
		a=false
		if [ ! -d /run/user/1000/gvfs/google-drive:host=g.jct.ac.il,user=darobins ]; then
			zenity --notification --text="Google-Drive isn't mounted.\n mounting..."
			gio mount -d google-drive://darobins@g.jct.ac.il/
			a=true
		fi
		cp -ru /home/david/Documents/JCT/* /run/user/1000/gvfs/google-drive:host=g.jct.ac.il,user=darobins/0AP9mfGUWSOGXUk9PVA/1H8Pw_zuGgeWlcMV2tCygc72L_sktv9YQ/ #| zenity --progress --percentage=0 --auto-kill --text="updating 'google drive'..."
		if $a; then
			while true; do
				gio mount -u google-drive://darobins@g.jct.ac.il/ && break
				sleep 5m
			done
		fi
		break
	else
		zenity --notification --text="No internet connection"
	fi
	sleep 30m
done
unset GLOBIGNORE
exit 0